export const ACTION_TYPES = {
  SEARCH_SHOWS: "SEARCH_SHOWS",
  SET_lOADING: "SET_LOADING",
  SET_SINGLE_SHOW: "SET_SINGLE_SHOW",
  CLEAR_SINGLE_SHOW: "CLEAR_SINGLE_SHOW",
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
};
